sonar.projectKey=controle-financeiro-frontend
sonar.projectName=controle-financeiro-frontend
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/dist/**,**/node_modules/**
